services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:16.3-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env.local
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - form-action-db:/var/lib/postgresql/data
volumes:
  form-action-db:
